import { useState } from 'react';
import { Check, Clock3, Computer, Moon, Palette, SlidersHorizontal, Sun } from 'lucide-react';
import { Note, Toggle } from './components';
import type { Preferences } from './state';

interface Props { prefs: Preferences; update: (patch: Partial<Preferences>) => void; notify: (message: string) => void }
export function Settings({ prefs, update, notify }: Props) {
  const [tab, setTab] = useState('general');
  const change = (patch: Partial<Preferences>) => { update(patch); notify('偏好已保存 · 仅影响此浏览器原型'); };
  return <><div className="page-heading"><div><h1>设置</h1><p>让 Tibo Watch 按照你的习惯，安静运行。</p></div><span className="autosave"><Check size={15}/>偏好即时保存</span></div><div className="settings-layout"><nav className="settings-nav" aria-label="设置分类">{[['general', '常规与启动', SlidersHorizontal], ['appearance', '外观', Palette]].map(([id, label, Icon]) => { const NavIcon = Icon as typeof Palette; return <button key={String(id)} className={tab === id ? 'active' : ''} onClick={() => setTab(String(id))}><NavIcon size={19}/>{String(label)}</button>; })}<p>这里的设置只作用于原型，不会修改已安装的桌面应用。</p></nav><div className="settings-content">
      {tab === 'general' ? <><section className="panel settings-panel"><div className="panel-heading"><Clock3/><div><h2>监测节奏</h2><p>在及时性和安静运行之间，找到你的平衡。</p></div></div><div className="setting-row"><div><strong>检查间隔</strong><p>手动检查不受此间隔限制。</p></div><select aria-label="检查间隔" value={prefs.interval} onChange={event => change({ interval: event.target.value })}><option value="5">每 5 分钟</option><option value="10">每 10 分钟</option><option value="15">每 15 分钟</option><option value="30">每 30 分钟</option></select></div><div className="setting-row"><div><strong>显示时间</strong><p>公告、检查和送达记录统一使用北京时间。</p></div><span className="setting-value">UTC+8</span></div></section><section className="panel settings-panel"><div className="panel-heading"><Computer/><div><h2>启动与后台</h2><p>不用时收进托盘，需要时随时回来。</p></div></div>{(['autoStart', 'hidden', 'tray'] as const).map((key, index) => <div className="setting-row" key={key}><div><strong>{['开机自动启动', '开机时静默启动', '关闭窗口后继续监测'][index]}</strong><p>{['登录 Windows 后启动 Tibo Watch。', '只进入托盘，不弹出主窗口；手动打开不受影响。', '保留后台监测；从托盘「退出」才会停止。'][index]}</p></div><Toggle label={['开机自动启动', '开机时静默启动', '关闭窗口后继续监测'][index]!} checked={prefs[key]} disabled={key === 'hidden' && !prefs.autoStart} onChange={() => change({ [key]: !prefs[key] })}/></div>)}<Note>浏览器预览不会注册开机任务或创建系统托盘。</Note></section></> : null}
      {tab === 'appearance' ? <><section className="panel settings-panel"><div className="panel-heading"><Palette/><div><h2>外观</h2><p>一种清晰的秩序，两种舒适的光线。</p></div></div><div className="theme-options">{(['light', 'dark'] as const).map(theme => <button key={theme} aria-pressed={prefs.theme === theme} onClick={() => change({ theme })}><span className={`theme-swatch ${theme}`}><i/><i/><i/></span><span>{theme === 'light' ? <Sun size={17}/> : <Moon size={17}/>} {theme === 'light' ? '浅色 · 晨光' : '深色 · 夜航'}{prefs.theme === theme ? <Check size={16}/> : null}</span></button>)}</div></section></> : null}
    </div></div></>;
}
