import type { AppSnapshot } from '../shared/api';

export const demoSnapshot: AppSnapshot = {
  settings: {
    pollIntervalMinutes: 5,
    browserSourceEnabled: true,
    publicRssEnabled: true,
    startAtLogin: true,
    closeToTray: true,
    baselineComplete: true,
    onboardingComplete: true,
    emailEnabled: true,
    emailRecipients: ['me@example.com', 'you@example.com'],
    smtpHost: 'smtp.gmail.com',
    smtpPort: 587,
    smtpSecure: false,
    smtpUsername: 'thsottiaux@gmail.com',
    smtpFrom: 'Tibo Watch <thsottiaux@gmail.com>',
    hasSmtpPassword: true,
  },
  posts: [
    {
      post: {
        id: '1920812345678901234',
        authorHandle: 'thsottiaux',
        text: "I've reset usage limits for all ChatGPT Work and Codex users.",
        createdAt: '2025-05-08T06:28:45.000Z',
        url: 'https://x.com/thsottiaux/status/1920812345678901234',
        kind: 'original',
        quotedText: null,
        sourceIds: ['public-rss', 'x-browser'],
      },
      classification: {
        level: 'confirmed',
        score: 10,
        reasons: ['检测到 Tibo 明确声明已重置 Codex（及 ChatGPT Work）使用限制。'],
        matchedTerms: ['reset', 'usage limits', 'ChatGPT Work', 'Codex users'],
        classifierVersion: 'rules-v1',
      },
    },
    {
      post: {
        id: '1917965432109876543',
        authorHandle: 'thsottiaux',
        text: "We're working on increasing Codex usage limits.",
        createdAt: '2025-05-01T05:12:00.000Z',
        url: 'https://x.com/thsottiaux/status/1917965432109876543',
        kind: 'original',
        quotedText: null,
        sourceIds: ['public-rss'],
      },
      classification: {
        level: 'preview', score: 7, reasons: ['表达了未来调整额度的意图。'],
        matchedTerms: ['Codex', 'usage limits'], classifierVersion: 'rules-v1',
      },
    },
    {
      post: {
        id: '1916800000000000000', authorHandle: 'thsottiaux',
        text: 'Codex update: improved reliability and bug fixes.',
        createdAt: '2025-04-28T01:47:00.000Z', url: 'https://x.com/thsottiaux/status/1916800000000000000',
        kind: 'original', quotedText: null, sourceIds: ['x-browser'],
      },
      classification: { level: 'related', score: 3, reasons: ['涉及 Codex 上下文。'], matchedTerms: ['Codex'], classifierVersion: 'rules-v1' },
    },
  ],
  events: [],
  sourceHealth: [
    { sourceId: 'x-browser', label: 'X 登录抓取', state: 'online', consecutiveFailures: 0, lastCheckedAt: '2025-05-08T06:35:00.000Z', lastSuccessAt: '2025-05-08T06:35:00.000Z' },
    { sourceId: 'public-rss', label: '公共 RSS', state: 'online', consecutiveFailures: 0, lastCheckedAt: '2025-05-08T06:35:00.000Z', lastSuccessAt: '2025-05-08T06:35:00.000Z' },
  ],
  mailQueue: [],
  paused: false,
  checking: false,
  xLoggedIn: true,
  lastCheckedAt: '2025-05-08T06:35:00.000Z',
  nextCheckAt: '2025-05-08T06:40:00.000Z',
  version: '0.1.1',
};

export const emptySnapshot: AppSnapshot = {
  settings: {
    pollIntervalMinutes: 5,
    browserSourceEnabled: false,
    publicRssEnabled: true,
    startAtLogin: true,
    closeToTray: true,
    baselineComplete: false,
    onboardingComplete: false,
    emailEnabled: false,
    emailRecipients: [],
    smtpHost: '',
    smtpPort: 587,
    smtpSecure: false,
    smtpUsername: '',
    smtpFrom: '',
    hasSmtpPassword: false,
  },
  posts: [],
  events: [],
  sourceHealth: [],
  mailQueue: [],
  paused: false,
  checking: false,
  xLoggedIn: false,
  lastCheckedAt: null,
  nextCheckAt: null,
  version: '0.1.1',
};
